Improve signature handling with DNF
eclipse/packager pull request #44
Opened 2022-08-16 17:02 UTC by ctron

2022-08-16 23:06 UTC, dwalluck requested changes
Looks good to me. I marked some formatting (whitespace) issues I saw, but they are not important.

2022-08-16 23:06 UTC, dwalluck commented on rpm/src/main/java/org/eclipse/packager/rpm/app/Dumper.java
> +        final RpmLead lead = in.getLead();
Small formatting issue.

2022-08-16 23:06 UTC, dwalluck commented on rpm/src/main/java/org/eclipse/packager/rpm/build/PayloadProcessors.java
> +                header.putInt ( RpmTag.PAYLOAD_DIGEST_ALGO, algorithm.getTag() );
Small formatting issue.

2022-08-16 23:06 UTC, dwalluck commented on rpm/src/main/java/org/eclipse/packager/rpm/build/RpmBuilder.java
> +        this.header.putAll ( finished.getAdditionalHeader() );
Small formatting issue.

2022-08-16 23:06 UTC, dwalluck commented on rpm/src/main/java/org/eclipse/packager/rpm/build/RpmBuilder.java
> +                this.headerCustomizer.accept(this.header);
Small formatting issue.

2022-08-16 23:06 UTC, dwalluck commented on rpm/src/main/java/org/eclipse/packager/rpm/build/RpmBuilder.java
> +            try ( final RpmWriter writer = new RpmWriter ( this.targetFile, leadBuilder, this.header, this.options.getHeaderCharset (), this.options.getOpenOptions() ) ) {
Small formatting issue.

2022-08-16 23:06 UTC, dwalluck commented on rpm/src/main/java/org/eclipse/packager/rpm/signature/RsaSignatureProcessor.java
> +    protected RsaSignatureProcessor(final PGPPrivateKey privateKey, final int hashAlgorithm )
Small formatting issue.

2022-08-16 23:06 UTC, dwalluck commented on rpm/src/main/java/org/eclipse/packager/rpm/signature/RsaSignatureProcessor.java
> +        final BcPGPContentSignerBuilder contentSignerBuilder = new BcPGPContentSignerBuilder ( privateKey.getPublicKeyPacket ().getAlgorithm (), hashAlgorithm);
Small formatting issue.

2022-08-16 23:06 UTC, dwalluck commented on rpm/src/main/java/org/eclipse/packager/rpm/signature/RsaSignatureProcessor.java
> +            this.signatureGenerator.init ( PGPSignature.BINARY_DOCUMENT, privateKey);
Small formatting issue.

2022-08-16 23:06 UTC, dwalluck commented on rpm/src/main/java/org/eclipse/packager/rpm/signature/RsaSignatureProcessor.java
> +        try {
Small formatting issue. I think you have braces on their own lines normally.

2022-08-17 07:16 UTC, ctron commented
> Looks good to me. I marked some formatting (whitespace) issues I saw, but they are not important.

Thanks for finding all of these :) I am struggling with the formatting. I think it is time to move to some more standard formatting, and let the IDE do it. I will finish this up and create a PR which changes the formatting of the whole repository. So we can judge, discuss, and maybe merge.

2022-08-17 07:30 UTC, merged